# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VEHICLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_no', models.CharField(max_length=15)),
                ('Driver_name', models.CharField(max_length=25)),
                ('Mob_no', models.CharField(max_length=12)),
                ('Status', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=20)),
                ('Latitude', models.CharField(max_length=15)),
                ('Longitude', models.CharField(max_length=15)),
            ],
        ),
    ]
